[tools]
cosign = "latest"
go = "latest"
goreleaser = "latest"
svu = "latest"

[tasks.build]
description = "Build the CLI locally (pass `--snapshot` to build HEAD)"
run = "goreleaser build --clean"

[tasks.tag]
description = "Tag a new version"
run = "git tag $(svu next) && git push --tags"

[tasks.release]
description = "Release a new version"
run = "goreleaser release --auto-snapshot --clean"

[hooks]
enter = "mise install"

[settings]
experimental = true
